### ISSUE TITLE
What about a CommandProcessor for command name, options and arguments extra

### ISSUE THREAD

**Issue by jeromemacias** [Hexanet/MonologExtraBundle#30]
Nice bundle !

Can a `CommandProcessor` be useful (see https://github.com/otobank/monolog-console-processor/blob/master/src/ConsoleProcessor.php) ?

We could add 3 informations:
- name
- options
- arguments

**Comment by notFloran** [comment]
Nice idea ! And thanks for the PR.

**Comment by notFloran** [comment]
We will release a new version in the week.
